const SLIDES_DATA = [
  {
    "index": 1,
    "title": "Tại sao tắc kè bám được trên kính?",
    "category": "Mở đầu (Hook)",
    "description": "Làm sao tắc kè chạy được trên mặt kính nhẵn bóng?",
    "fullText": "Làm sao tắc kè chạy được trên mặt kính nhẵn bóng?",
    "image": "slides/slide_01.webp",
    "imagePng": "slides/slide_01.png",
    "thumb": "slides/thumb_01.webp",
    "transition": "none",
    "duration": 0,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 2,
    "title": "Lực Van der Waals",
    "category": "Tiêu đề chính",
    "description": "Người trình bày: Nguyễn Minh Trường",
    "fullText": "Lực Van der Waals \\n Nguyễn Minh Trường",
    "image": "slides/slide_02.webp",
    "imagePng": "slides/slide_02.png",
    "thumb": "slides/thumb_02.webp",
    "transition": "peelOff",
    "duration": 1250,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 3,
    "title": "Nội dung chính",
    "category": "Mục lục",
    "description": "5 phần: Nguồn gốc, Nguyên lý, Cảm hứng sinh học, Vật liệu Nano, Tổng kết & Tương lai",
    "fullText": "Nội dung chính \\n 1. Nguồn gốc của lực Van der Waals\r2. Nguyên lý cơ bản\r3. Ứng dụng cảm hứng sinh học\r4. Ứng dụng trong vật liệu Nano tiên tiến\r5. Tổng kết & Tương lai",
    "image": "slides/slide_03.webp",
    "imagePng": "slides/slide_03.png",
    "thumb": "slides/thumb_03.webp",
    "transition": "morph",
    "duration": 2000,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 4,
    "title": "Johannes Diderik van der Waals",
    "category": "1. Nguồn gốc của lực Van der Waals",
    "description": "Giải Nobel Vật lý 1910 - Chân dung & Huy chương",
    "fullText": "1. Nguồn gốc của lực Van der Waals \\n Johannes Diderik van der Waals \\n Giải Nobel Vật lý 1910 \\n Chân dung Waals",
    "image": "slides/slide_04.webp",
    "imagePng": "slides/slide_04.png",
    "thumb": "slides/thumb_04.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 5,
    "title": "Khám phá từ một Luận án (1873)",
    "category": "1. Nguồn gốc của lực Van der Waals",
    "description": "Khí thực không hoàn toàn tuân theo định luật khí lí tưởng",
    "fullText": "1. Nguồn gốc của lực Van der Waals \\n Khám phá từ một Luận án (1873) \\n Khí thực không hoàn toàn tuân theo định luật khí lý tưởng. \\n Ông đề xuất:\u000b1. Các phân tử có thể tích thực\u000b2. Tồn tại một lực hút yếu giữa chúng.",
    "image": "slides/slide_05.webp",
    "imagePng": "slides/slide_05.png",
    "thumb": "slides/thumb_05.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 6,
    "title": "Phương trình Van der Waals",
    "category": "1. Nguồn gốc của lực Van der Waals",
    "description": "So sánh phương trình khí lí tưởng pV=nRT và phương trình Van der Waals",
    "fullText": "1. Nguồn gốc của lực Van der Waals \\n Khám phá từ một Luận án (1873) \\n Phương trình khí lí tưởng \\n 𝑝+ 𝑎 𝑛 2   𝑉 2    𝑉−𝑛𝑏 =𝑛𝑅𝑇​ \\n pV = nRT \\n Phương trình Van der Waals \\n b: Hằng số đại diện thể tích thực\r𝑎 : Hằng số đại diện lực hút tĩnh điện (lực Van der Waals) \\n Khí lí tưởng bỏ qua thể tích thực phân tử và tương tác giữa phân tử khí",
    "image": "slides/slide_06.webp",
    "imagePng": "slides/slide_06.png",
    "thumb": "slides/thumb_06.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 7,
    "title": "Sức mạnh của sự nhỏ bé",
    "category": "2. Nguyên lý cơ bản",
    "description": "Sự phân bố electron không đồng đều tạo lưỡng cực tạm thời (Hoạt ảnh tương tác phân tử)",
    "fullText": "2. Nguyên lý cơ bản \\n Sức mạnh của sự nhỏ bé \\n Sự phân bố electron không đồng đều tạo lưỡng cực tạm thời",
    "image": "slides/slide_07.webp",
    "imagePng": "slides/slide_07.png",
    "thumb": "slides/thumb_07.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": true,
    "mediaType": "gif",
    "mediaSrc": "assets/vdw_molecules.gif"
  },
  {
    "index": 8,
    "title": "Cơ chế tương tác phân tử (Sơ đồ 1)",
    "category": "2. Nguyên lý cơ bản",
    "description": "Cơ chế cảm ứng và phân cực điện tích tạm thời",
    "fullText": "2. Nguyên lý cơ bản \\n Cơ chế tương tác phân tử",
    "image": "slides/slide_08.webp",
    "imagePng": "slides/slide_08.png",
    "thumb": "slides/thumb_08.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 9,
    "title": "Cơ chế tương tác phân tử (Sơ đồ 2)",
    "category": "2. Nguyên lý cơ bản",
    "description": "Khoảng cách Van der Waals và điểm cân bằng thế năng",
    "fullText": "2. Nguyên lý cơ bản \\n Cơ chế tương tác phân tử",
    "image": "slides/slide_09.webp",
    "imagePng": "slides/slide_09.png",
    "thumb": "slides/thumb_09.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 10,
    "title": "Cấu trúc Setae & Spatulae",
    "category": "3. Ứng dụng cảm hứng sinh học",
    "description": "Cấu trúc các sợi vi mô ở bàn chân thằn lằn / tắc kè",
    "fullText": "3. Ứng dụng cảm hứng sinh học \\n Cấu trúc Setae & Spatulae \\n Cấu trúc các sợi vi mô ở bàn chân thằn lằn",
    "image": "slides/slide_10.webp",
    "imagePng": "slides/slide_10.png",
    "thumb": "slides/thumb_10.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 11,
    "title": "Găng tay Geckskin",
    "category": "3. Ứng dụng cảm hứng sinh học",
    "description": "Ứng dụng leo trèo trần kính, chịu tải trọng lớn không để lại keo",
    "fullText": "3. Ứng dụng cảm hứng sinh học \\n Găng tay Geckskin",
    "image": "slides/slide_11.webp",
    "imagePng": "slides/slide_11.png",
    "thumb": "slides/thumb_11.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 12,
    "title": "Sợi Microfiber - Cấu trúc",
    "category": "3. Ứng dụng cảm hứng sinh học",
    "description": "Tạo thành từ Polyester và Polyamide với sợi siêu mịn",
    "fullText": "3. Ứng dụng cảm hứng sinh học \\n Sợi Microfiber \\n Tạo thành từ Polyester và Polyamide",
    "image": "slides/slide_12.webp",
    "imagePng": "slides/slide_12.png",
    "thumb": "slides/thumb_12.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 13,
    "title": "Sợi Microfiber - Ứng dụng",
    "category": "3. Ứng dụng cảm hứng sinh học",
    "description": "Khăn lau kính cận và thiết bị quang học",
    "fullText": "3. Ứng dụng cảm hứng sinh học \\n Sợi Microfiber \\n Khăn lau kính cận",
    "image": "slides/slide_13.webp",
    "imagePng": "slides/slide_13.png",
    "thumb": "slides/thumb_13.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 14,
    "title": "Băng dính y tế sinh học",
    "category": "3. Ứng dụng cảm hứng sinh học",
    "description": "Không dùng keo dính thông thường, không gây đau khi bóc khỏi da",
    "fullText": "3. Ứng dụng cảm hứng sinh học \\n Băng dính y tế sinh học \\n Không dùng keo nên không gây đau khi bóc",
    "image": "slides/slide_14.webp",
    "imagePng": "slides/slide_14.png",
    "thumb": "slides/thumb_14.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 15,
    "title": "Tay gắp Robot",
    "category": "3. Ứng dụng cảm hứng sinh học",
    "description": "Gắp dính vật liệu phẳng mỏng với lực kẹp cực nhẹ",
    "fullText": "3. Ứng dụng cảm hứng sinh học \\n Tay gắp Robot \\n Gắp dính với lực gắp rất nhẹ",
    "image": "slides/slide_15.webp",
    "imagePng": "slides/slide_15.png",
    "thumb": "slides/thumb_15.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 16,
    "title": "Vật liệu 2D (Heterostructures)",
    "category": "4. Ứng dụng trong vật liệu Nano tiên tiến",
    "description": "Xếp chồng từng lớp nguyên tử chỉ bằng lực hút yếu Van der Waals",
    "fullText": "4. Ứng dụng trong vật liệu Nano tiên tiến \\n Vật liệu 2D (Heterostructures) \\n Xếp chồng từng lớp nguyên tử chỉ bằng lực hút yếu",
    "image": "slides/slide_16.webp",
    "imagePng": "slides/slide_16.png",
    "thumb": "slides/thumb_16.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 17,
    "title": "Ống Nano Carbon (CNTs)",
    "category": "4. Ứng dụng trong vật liệu Nano tiên tiến",
    "description": "Tự liên kết và kết bó nhờ lực hút yếu bền vững",
    "fullText": "4. Ứng dụng trong vật liệu Nano tiên tiến \\n Ống Nano Carbon (CNTs) \\n Tự liên kết nhờ lực hút yếu",
    "image": "slides/slide_17.webp",
    "imagePng": "slides/slide_17.png",
    "thumb": "slides/thumb_17.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 18,
    "title": "Micro-robots",
    "category": "4. Ứng dụng trong vật liệu Nano tiên tiến",
    "description": "Di chuyển linh hoạt trên các bề mặt bằng lực hút phân tử",
    "fullText": "4. Ứng dụng trong vật liệu Nano tiên tiến \\n Micro-robots \\n Di chuyển bằng lực hút phân tử",
    "image": "slides/slide_18.webp",
    "imagePng": "slides/slide_18.png",
    "thumb": "slides/thumb_18.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 19,
    "title": "Bề mặt tự làm sạch",
    "category": "4. Ứng dụng trong vật liệu Nano tiên tiến",
    "description": "Dựa vào hiệu ứng lá sen và độ bám dính nano",
    "fullText": "4. Ứng dụng trong vật liệu Nano tiên tiến \\n Bề mặt tự làm sạch \\n Dựa vào hiệu ứng lá sen",
    "image": "slides/slide_19.webp",
    "imagePng": "slides/slide_19.png",
    "thumb": "slides/thumb_19.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 20,
    "title": "Vai trò cốt lõi trong công nghệ mới",
    "category": "5. Tổng kết & Tương lai",
    "description": "Cầu nối giữa thế giới vi mô và ứng dụng vĩ mô tương lai",
    "fullText": "5. Tổng kết & Tương lai \\n Vai trò cốt lõi trong công nghệ mới \\n Dù là lực tương tác yếu, Van der Waals lại là chìa khóa mở ra các công nghệ tương lai. \\n • Sinh học & Y tế: Băng dính y sinh học an toàn, không hóa chất.\u000b• Robot & Tự động hóa: Đệm gắp siêu việt, không làm tổn hại vật liệu mỏng.\u000b• Vật liệu Nano: Nền tảng xếp chồng các màng vật liệu 2D siêu mỏng.",
    "image": "slides/slide_20.webp",
    "imagePng": "slides/slide_20.png",
    "thumb": "slides/thumb_20.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  },
  {
    "index": 21,
    "title": "Lực nhỏ bé, sức mạnh vĩ đại",
    "category": "5. Tổng kết & Tương lai",
    "description": "Cảm ơn bạn đã lắng nghe! Q & A",
    "fullText": "Lực nhỏ bé, sức mạnh vĩ đại \\n Cảm ơn bạn đã lắng nghe!\u000bQ & A",
    "image": "slides/slide_21.webp",
    "imagePng": "slides/slide_21.png",
    "thumb": "slides/thumb_21.webp",
    "transition": "fade",
    "duration": 700,
    "hasMedia": false,
    "mediaType": null,
    "mediaSrc": null
  }
];
